-- Run in Supabase SQL Editor for this friends-only travel vote app.
-- The browser uses only the anon/publishable key. Never expose a service-role key.

create table if not exists public.accommodations (
  id text primary key,
  trip_slug text not null,
  name text not null,
  area text,
  price_total text,
  price_per_person text,
  sauna text,
  bbq text,
  access text,
  summary text,
  url text,
  image_url text,
  sort_order int default 0
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  trip_slug text not null,
  voter_name text not null check (char_length(voter_name) between 1 and 30),
  accommodation_id text not null,
  score int not null check (score between 1 and 5),
  updated_at timestamptz not null default now(),
  unique (trip_slug, voter_name, accommodation_id)
);

alter table public.accommodations enable row level security;
alter table public.votes enable row level security;

-- Public read of candidate metadata. Candidate editing remains SQL/dashboard-only.
drop policy if exists "anon read accommodations" on public.accommodations;
create policy "anon read accommodations" on public.accommodations for select to anon using (true);

-- Friends-only, no-login voting: anyone with the public page can read/write votes.
-- This is intentionally simple, not identity-secure. Use Supabase Auth for stronger guarantees.
drop policy if exists "anon read votes" on public.votes;
create policy "anon read votes" on public.votes for select to anon using (true);
drop policy if exists "anon insert votes" on public.votes;
create policy "anon insert votes" on public.votes for insert to anon with check (true);
drop policy if exists "anon update votes" on public.votes;
create policy "anon update votes" on public.votes for update to anon using (true) with check (true);
drop policy if exists "anon delete votes" on public.votes;
create policy "anon delete votes" on public.votes for delete to anon using (true);

insert into public.accommodations (id,trip_slug,name,area,price_total,price_per_person,sauna,bbq,access,summary,sort_order) values
('bros-resort-kyonan','nokogiriyama-sauna-2026','BROS RESORT KYONAN','鋸南','要確認','日程により変動','屋内＋屋外サウナ / 水風呂 / ジャグジー','あり','鋸山周辺・鋸南エリア','サウナ設備をしっかり楽しみたいグループ向けの一棟貸し。',1),
('villa-asile','nokogiriyama-sauna-2026','VILLA Asile','金谷','約99,000円〜 / 5人','約19,800円〜 / 人','バレルサウナ / 水風呂 / プール','要確認','鋸山・金谷エリアでアクセス良好','プールとサウナを備えた、上質感のあるヴィラ。',2),
('bask-hota','nokogiriyama-sauna-2026','BASK HOTA','保田','約52,000〜75,000円〜 / 5人','約10,400〜15,000円〜 / 人','サウナあり（詳細は予約ページで確認）','要確認','鋸山に近い保田エリア','鋸山への近さと価格バランスを重視した候補。',3),
('d6-makiwarina','nokogiriyama-sauna-2026','D6 Makiwarina 薪割りーな','鋸南 / 大六','約42,000円〜','約8,400円〜 / 人（5人換算）','薪サウナ','あり','鋸南・大六エリア','薪サウナとBBQをカジュアルに楽しめるコスパ重視候補。',4),
('ocean-sauna-villa-takeoka','nokogiriyama-sauna-2026','Ocean Sauna Villa 富津竹岡 by GIFTHOUSE','竹岡','要確認','日程により変動','イグルー型サウナ / 水風呂','要確認','富津竹岡から鋸山方面へアクセス','海辺のプライベート空間と個性的なサウナを楽しめるヴィラ。',5)
on conflict (id) do update set
  trip_slug=excluded.trip_slug,name=excluded.name,area=excluded.area,price_total=excluded.price_total,
  price_per_person=excluded.price_per_person,sauna=excluded.sauna,bbq=excluded.bbq,access=excluded.access,
  summary=excluded.summary,sort_order=excluded.sort_order;
